# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rack-domain_redirect 0.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "rack-domain_redirect"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Michal Pawlowski"]
  s.date = "2015-01-06"
  s.description = "\nRack::DomainRedirect is a tiny rack middleware for redirecting to the\nconfigurable domain. If user request's the service from domain other than that\nconfigured it redirects to the first domain on the configuration list. If no\ndomain is configured it does noting and passes requests to another application\nin the chain."
  s.email = "misza222@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "example/config.ru",
    "lib/rack/domain_redirect.rb",
    "test/test_domain_redirect.rb"
  ]
  s.homepage = "http://github.com/misza222/rack-domain_redirect"
  s.rubygems_version = "2.2.2"
  s.summary = "Rack::DomainRedirect redirects to the configurable domain."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 2"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5"])
      s.add_runtime_dependency(%q<rack>, [">= 1.1"])
    else
      s.add_dependency(%q<shoulda>, [">= 2"])
      s.add_dependency(%q<rack-test>, [">= 0.5"])
      s.add_dependency(%q<rack>, [">= 1.1"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 2"])
    s.add_dependency(%q<rack-test>, [">= 0.5"])
    s.add_dependency(%q<rack>, [">= 1.1"])
  end
end

